const projectArray = [
  {
    id: "1",
    title: "AstronoME",
    src: "/AstronoME.png",
    description: 'React Application built for stargazers. Provides information about current moon phase, weather, and incoming asteroids. and it contains a fully functional forum for stargazers to connect and share what they see.',
    link: "https://astronome-10022023-9058067b996b.herokuapp.com/",
    github: "https://github.com/cdgonzo23/astronoME",
    caseStudy: "Astronome",
  },
  {
    id: "2",
    title: "Maintenance Manatee",
    src: "/Maintenance-Manatee.png",
    description: 'Interactive Full-Stack Web Application that stores users car data as well as maintenance done on their vehicles. Uses Node.js to create a RESTful API, Sequelize for the databse, and Handlebars.js for the template.',
    link: "https://maintenance-manatee-20230807-e071f072b462.herokuapp.com/",
    github: "https://github.com/cdgonzo23/maintenance-manatee",
    caseStudy: "MaintenanceManatee",
  },
  {
    id: "3",
    title: "Book Search Refactor",
    src: "/Book-Search.png",
    description: 'Code Refactor project. Utilize Apollo/Server and GraphQL instead of RESTful API',
    link: "https://cdgonzo23.github.io/code-quiz/",
    github: "https://github.com/cdgonzo23/code-quiz",
    caseStudy: "BookSearchRefactor",
  },

  {
    id: "4",
    title: "PWA Text Editor",
    src: "/J-A-T-E.png",
    description: 'An installable text editor that saves code snippets with the correct color formatting. Works offline and online',
    link: "https://another-text-editor-040923-3c59dc8eb62b.herokuapp.com/",
    github: "https://github.com/cdgonzo23/pwa-text-editor",
    caseStudy: "PWATextEditor",
  },
  {
    id: "5",
    title: "Tech Blog",
    src: "/tech-blog.png",
    description: 'A CMS style blog created for developers to publish blog posts and comment on other users post. Uses Sequelize and Handlebars.',
    link: "https://mvc-tech-blog-20230802-f118edb4f2ae.herokuapp.com/",
    github: "https://github.com/cdgonzo23/tech-blog",
    caseStudy: "TechBlog",
  },
  {
    id: "6",
    title: "Night-In Generator",
    src: "/night-in-generator.png",
    description: 'Interactive Front-End Application that generates a meal, drink, and movie combination for users to plan a nice night-in for themselves.',
    link: "https://cdgonzo23.github.io/night-in-generator/",
    github: "https://github.com/cdgonzo23/night-in-generator",
    caseStudy: "NightInGenerator",
  },
  {
    id: "7",
    title: "Social Network API",
    mp4: "/social-network.mp4",
    description: 'Social Network API where users can post thoughts, connect with friends, and react to friends thoughts. Uses MongoDB and Mongoose ODM.',
    github: "https://github.com/cdgonzo23/social-network-api",
    caseStudy: "SocialNetworkAPI",
  },
  {
    id: "8",
    title: "E-Commerce Back End",
    mp4: "/e-commerce.mp4",
    description: 'An E-Commerce back-end application using SQL to view, add, edit, and delete products, categories, and tags',
    github: "https://github.com/cdgonzo23/e-commerce-back-end",
    caseStudy: "ECommerceBackEnd",
  },
];

export default projectArray;
